#server:
#  port: 8787
#
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/yun?serverTimezone=UTC
#      username: root
#      password:
#
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: t_
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志配置
logging:
  level:
    root: info
    com.itheima: debug
